"""link users to posts and social accounts

Revision ID: 0fe941198ce7
Revises: 88bd0c04c55d
Create Date: 2026-07-28 10:44:02.777885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe941198ce7'
down_revision: Union[str, Sequence[str], None] = '88bd0c04c55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.add_column('social_accounts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'social_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_column('social_accounts', 'user_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
