"""initial content schema

Revision ID: d38120e4785a
Revises: 
Create Date: 2026-07-24 14:24:41.518984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd38120e4785a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommended_candidate_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('suggested_media', sa.Text(), nullable=False),
    sa.Column('hook_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('brand_score', sa.Integer(), nullable=False),
    sa.Column('readability_score', sa.Integer(), nullable=False),
    sa.Column('cta_score', sa.Integer(), nullable=False),
    sa.Column('platform_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evaluation_explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_candidates_generation_id'), 'content_candidates', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_candidates_generation_id'), table_name='content_candidates')
    op.drop_table('content_candidates')
    op.drop_table('content_generations')
    # ### end Alembic commands ###
