"""add user to content generations

Revision ID: d4e87e308b12
Revises: 0fe941198ce7
Create Date: 2026-07-28 11:43:06.672717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e87e308b12'
down_revision: Union[str, Sequence[str], None] = '0fe941198ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_generations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_content_generations_user_id'), 'content_generations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'content_generations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_generations', type_='foreignkey')
    op.drop_index(op.f('ix_content_generations_user_id'), table_name='content_generations')
    op.drop_column('content_generations', 'user_id')
    # ### end Alembic commands ###
